### ISSUE TITLE
Some images from Lecture 14 notebook are missing

### ISSUE THREAD

**Issue by alexandremuzio** [cuda-mode/lectures#16]
Hello,

@UmerHA , thanks a lot for your awesome notebook!
It seems some of the images are missing from the notebook, I'm wondering if you could update them.
Thanks in advance!

Example:
<img width="668" alt="image" src="https://github.com/cuda-mode/lectures/assets/3949616/66179ba6-d423-41b1-bcd1-698ae175d818">

**Comment by UmerHA** [comment]
Hi thanks, my hypothesis is GitHub deletes large notebook metadata, and the images are saved as metadata in the notebook.

I'll reduce image sizes and try again!

**Comment by UmerHA** [comment]
I've now put the images into separate files. Let me know if you still have an issue (after #17 is merged)
