### ISSUE TITLE
motion pictures 📽️

### ISSUE THREAD

**Issue by aretrace** [cuda-mode/lectures#8]
### 🎞️ 🤷
where them video links for the lectures (if recording available of course)

**Comment by andreaskoepf** [comment]
You can find recordings of all lecture here: https://www.youtube.com/@CUDAMODE

**Comment by andreaskoepf** [comment]
You find recordings of our lectures on our cuda-mode youtube channel: https://www.youtube.com/@CUDAMODE

**Comment by aretrace** [comment]
Thank you for 1925780!
